import type {
  Activity,
  AuditResult,
  Client,
  ClientReport,
  ClientRequest,
  Deal,
  Lead,
  Offer,
  OutreachDraft,
  Proposal,
  QaReview,
  Task,
  TimeEntry,
  Vendor,
} from "./types";

export const SEED_LEADS: Lead[] = [
  {
    id: "lead-01",
    company: "Northbridge Dental Group",
    website: "https://northbridge.example",
    country: "United Kingdom",
    industry: "Healthcare",
    contactName: "Rachel Cole",
    contactTitle: "Operations Director",
    email: "rachel.cole@northbridge.example",
    linkedin: "https://linkedin.com/in/example-rcole",
    phone: "+44 20 7946 0101",
    source: "Website audit",
    status: "won",
    score: 91,
    notes: "Five clinics. Reception misses 30% of inbound. Wants booked consults, not a new phone system.",
    painPoints: ["Unanswered inbound", "Empty hygienist chairs", "No after-hours coverage"],
    suggestedOffer: "Appointment setting — 30 qualified consults / month",
    hiringSignal: true,
    outsourcingIntent: true,
    employees: "51-200",
    createdAt: "2026-06-12",
    nextAction: "QBRs monthly",
    nextActionAt: "2026-10-03",
  },
  {
    id: "lead-02",
    company: "Helios Freight",
    website: "https://heliosfreight.example",
    country: "United States",
    industry: "Logistics",
    contactName: "Marcus Hale",
    contactTitle: "VP Customer Experience",
    email: "mhale@heliosfreight.example",
    linkedin: "https://linkedin.com/in/example-mhale",
    phone: "+1 312 555 0144",
    source: "Intro",
    status: "won",
    score: 88,
    notes: "Tracking emails swamp the CS team after 18:00 CT. Need coverage, not a chatbot experiment.",
    painPoints: ["After-hours ticket pile", "CSAT 3.6", "No weekend cover"],
    suggestedOffer: "Chat & email support — 12h coverage",
    hiringSignal: true,
    outsourcingIntent: true,
    employees: "51-200",
    createdAt: "2026-05-03",
    nextAction: "Renewal conversation",
    nextActionAt: "2026-11-01",
  },
  {
    id: "lead-03",
    company: "Oak & Pine Interiors",
    website: "https://oakandpine.example",
    country: "Australia",
    industry: "Retail",
    contactName: "Elena Park",
    contactTitle: "Founder",
    email: "elena@oakandpine.example",
    linkedin: "https://linkedin.com/in/example-epark",
    phone: "+61 2 5550 0199",
    source: "LinkedIn",
    status: "won",
    score: 84,
    notes: "Wholesale buyers in UK/US. Founder doing all outreach. Wants a list + first-touch drafts, she sends.",
    painPoints: ["Founder-led prospecting", "Thin pipeline", "No CRM hygiene"],
    suggestedOffer: "Lead generation — 40 verified buyers / month",
    hiringSignal: false,
    outsourcingIntent: true,
    employees: "11-50",
    createdAt: "2026-07-01",
    nextAction: "Send September list",
    nextActionAt: "2026-09-18",
  },
  {
    id: "lead-04",
    company: "Meridian Chambers",
    website: "https://meridianchambers.example",
    country: "United Kingdom",
    industry: "Legal",
    contactName: "James Whitaker",
    contactTitle: "Practice Manager",
    email: "j.whitaker@meridianchambers.example",
    linkedin: "https://linkedin.com/in/example-jwhitaker",
    phone: "+44 161 555 0172",
    source: "Referral",
    status: "won",
    score: 79,
    notes: "Bundles, diaries, billing packs. Strict confidentiality. NDA already signed.",
    painPoints: ["Diary clashes", "Billing lag", "Fee-earner admin"],
    suggestedOffer: "Admin / VA — chambers pack",
    hiringSignal: true,
    outsourcingIntent: true,
    employees: "11-50",
    createdAt: "2026-04-18",
    nextAction: "QA review Friday",
    nextActionAt: "2026-09-19",
  },
  {
    id: "lead-05",
    company: "Brightlane Solar",
    website: "https://brightlane.example",
    country: "United States",
    industry: "Energy",
    contactName: "Sofia Alvarez",
    contactTitle: "Head of Sales",
    email: "sofia@brightlane.example",
    linkedin: "https://linkedin.com/in/example-salvarez",
    phone: "+1 480 555 0160",
    source: "Job board",
    status: "proposal_sent",
    score: 86,
    notes: "Posted for SDRs. Better fit: appointment setting against their closer calendar.",
    painPoints: ["SDR ramp too slow", "Calendar empty before 11am", "High CAC"],
    suggestedOffer: "Appointment setting — 40 qualified homeowner consults",
    hiringSignal: true,
    outsourcingIntent: true,
    employees: "51-200",
    createdAt: "2026-09-02",
    nextAction: "Follow up proposal",
    nextActionAt: "2026-09-17",
  },
  {
    id: "lead-06",
    company: "Kestrel Analytics",
    website: "https://kestrel.example",
    country: "Canada",
    industry: "SaaS",
    contactName: "Priya Nair",
    contactTitle: "COO",
    email: "priya@kestrel.example",
    linkedin: "https://linkedin.com/in/example-pnair",
    phone: "+1 416 555 0133",
    source: "Website audit",
    status: "call_booked",
    score: 82,
    notes: "No live chat. Docs are thin. Support is two engineers. Audit sent.",
    painPoints: ["Engineers on support", "No chat", "Slow first response"],
    suggestedOffer: "Inbound support — L1 with escalation",
    hiringSignal: true,
    outsourcingIntent: false,
    employees: "11-50",
    createdAt: "2026-09-08",
    nextAction: "Discovery call 17 Sep 16:00 SAST",
    nextActionAt: "2026-09-17",
  },
  {
    id: "lead-07",
    company: "Harbour & Co. Wealth",
    website: "https://harbourco.example",
    country: "United Kingdom",
    industry: "Finance",
    contactName: "Oliver Grant",
    contactTitle: "Partner",
    email: "ogrant@harbourco.example",
    linkedin: "https://linkedin.com/in/example-ogrant",
    phone: "+44 20 7946 1888",
    source: "LinkedIn",
    status: "replied",
    score: 74,
    notes: "Asked for a one-pager. Compliance-heavy. Do not oversell AI.",
    painPoints: ["Advisor inbox", "Onboarding packs slow"],
    suggestedOffer: "Admin / VA — client onboarding packs",
    hiringSignal: false,
    outsourcingIntent: true,
    employees: "11-50",
    createdAt: "2026-09-05",
    nextAction: "Send conservative one-pager",
    nextActionAt: "2026-09-16",
  },
  {
    id: "lead-08",
    company: "Nimbus Apparel",
    website: "https://nimbusapparel.example",
    country: "United States",
    industry: "DTC",
    contactName: "Ava Chen",
    contactTitle: "CX Lead",
    email: "ava@nimbusapparel.example",
    linkedin: "https://linkedin.com/in/example-achen",
    phone: "+1 213 555 0190",
    source: "Cold email",
    status: "contacted",
    score: 71,
    notes: "Returns season incoming. Chat widget is Intercom with nobody on it after 5pm PT.",
    painPoints: ["Seasonal spike", "Empty Intercom", "Refund tickets"],
    suggestedOffer: "Chat & email support — peak cover",
    hiringSignal: true,
    outsourcingIntent: false,
    employees: "51-200",
    createdAt: "2026-09-10",
    nextAction: "Bump email",
    nextActionAt: "2026-09-16",
  },
  {
    id: "lead-09",
    company: "Fieldwork Geotech",
    website: "https://fieldworkgeo.example",
    country: "Australia",
    industry: "Engineering",
    contactName: "Tom Reeve",
    contactTitle: "Managing Director",
    email: "tom@fieldworkgeo.example",
    linkedin: "https://linkedin.com/in/example-treeve",
    phone: "+61 7 5550 0440",
    source: "Website audit",
    status: "researched",
    score: 68,
    notes: "Site has no contact SLA. Quotes take 9 days. Tender admin is the leak.",
    painPoints: ["Slow quotes", "Tender admin", "No after-hours"],
    suggestedOffer: "Admin / VA — tender desk",
    hiringSignal: false,
    outsourcingIntent: false,
    employees: "11-50",
    createdAt: "2026-09-12",
    nextAction: "Finish audit and send",
    nextActionAt: "2026-09-16",
  },
  {
    id: "lead-10",
    company: "Copperline HVAC",
    website: "https://copperline.example",
    country: "United States",
    industry: "Home services",
    contactName: "Derek Holt",
    contactTitle: "Owner",
    email: "derek@copperline.example",
    linkedin: "",
    phone: "+1 702 555 0112",
    source: "Job board",
    status: "new_lead",
    score: 64,
    notes: "Posted on Upwork for a VA. Classic mis-scoped. Reframe as booked estimates.",
    painPoints: ["Missed after-hours calls", "Tech calendar holes"],
    suggestedOffer: "Appointment setting — booked estimates",
    hiringSignal: true,
    outsourcingIntent: true,
    employees: "1-10",
    createdAt: "2026-09-15",
    nextAction: "Score + draft job-board reply",
    nextActionAt: "2026-09-16",
  },
  {
    id: "lead-11",
    company: "Lumen Studio",
    website: "https://lumenstudio.example",
    country: "Netherlands",
    industry: "Design agency",
    contactName: "Mila Vos",
    contactTitle: "Producer",
    email: "mila@lumenstudio.example",
    linkedin: "https://linkedin.com/in/example-mvos",
    phone: "+31 20 555 0188",
    source: "Referral",
    status: "lost",
    score: 55,
    notes: "Wanted a $12/h generalist. Walked. Wrong buyer.",
    painPoints: ["Production admin"],
    suggestedOffer: "Admin / VA",
    hiringSignal: false,
    outsourcingIntent: true,
    employees: "1-10",
    createdAt: "2026-08-20",
    nextAction: "Leave in lost — cheap-labour buyer",
    nextActionAt: "2026-12-01",
  },
  {
    id: "lead-12",
    company: "Aster Clinics",
    website: "https://asterclinics.example",
    country: "United Kingdom",
    industry: "Healthcare",
    contactName: "Hannah Briggs",
    contactTitle: "Clinic Manager",
    email: "hannah@asterclinics.example",
    linkedin: "https://linkedin.com/in/example-hbriggs",
    phone: "+44 113 555 0166",
    source: "Website audit",
    status: "negotiation",
    score: 80,
    notes: "Likes the offer. Pushing for 28% margin. Hold the line at 45%.",
    painPoints: ["No-shows", "Unfilled slots"],
    suggestedOffer: "Appointment setting — recall + new",
    hiringSignal: true,
    outsourcingIntent: true,
    employees: "11-50",
    createdAt: "2026-08-28",
    nextAction: "Hold margin, offer a 30-day pilot volume",
    nextActionAt: "2026-09-18",
  },
];

export const SEED_DEALS: Deal[] = [
  { id: "deal-01", leadId: "lead-01", title: "Northbridge retainers", stage: "won", valueUsd: 4200, probability: 100, expectedClose: "2026-06-20", nextAction: "Live", owner: "You", notes: "Setup R paid.", lostReason: "", createdAt: "2026-06-12" },
  { id: "deal-02", leadId: "lead-02", title: "Helios CX cover", stage: "won", valueUsd: 6800, probability: 100, expectedClose: "2026-05-20", nextAction: "Live", owner: "You", notes: "Weekend cover added Aug.", lostReason: "", createdAt: "2026-05-03" },
  { id: "deal-03", leadId: "lead-03", title: "Oak & Pine buyers desk", stage: "won", valueUsd: 3500, probability: 100, expectedClose: "2026-07-12", nextAction: "Live", owner: "You", notes: "", lostReason: "", createdAt: "2026-07-01" },
  { id: "deal-04", leadId: "lead-04", title: "Meridian chambers pack", stage: "won", valueUsd: 2900, probability: 100, expectedClose: "2026-05-02", nextAction: "Live", owner: "You", notes: "NDA + ISO-style access log.", lostReason: "", createdAt: "2026-04-18" },
  { id: "deal-05", leadId: "lead-05", title: "Brightlane 40 consults", stage: "proposal_sent", valueUsd: 5400, probability: 55, expectedClose: "2026-09-30", nextAction: "Nudge Sofia", owner: "You", notes: "Proposal v2 sent 12 Sep.", lostReason: "", createdAt: "2026-09-02" },
  { id: "deal-06", leadId: "lead-06", title: "Kestrel L1 support", stage: "call_booked", valueUsd: 4800, probability: 40, expectedClose: "2026-10-10", nextAction: "Run discovery", owner: "You", notes: "", lostReason: "", createdAt: "2026-09-08" },
  { id: "deal-07", leadId: "lead-07", title: "Harbour onboarding packs", stage: "replied", valueUsd: 2600, probability: 30, expectedClose: "2026-10-15", nextAction: "One-pager", owner: "You", notes: "Compliance tone.", lostReason: "", createdAt: "2026-09-05" },
  { id: "deal-08", leadId: "lead-08", title: "Nimbus peak CX", stage: "contacted", valueUsd: 5100, probability: 20, expectedClose: "2026-10-20", nextAction: "Bump", owner: "You", notes: "", lostReason: "", createdAt: "2026-09-10" },
  { id: "deal-09", leadId: "lead-09", title: "Fieldwork tender desk", stage: "researched", valueUsd: 2400, probability: 15, expectedClose: "2026-10-30", nextAction: "Send audit", owner: "You", notes: "", lostReason: "", createdAt: "2026-09-12" },
  { id: "deal-10", leadId: "lead-10", title: "Copperline estimates", stage: "new_lead", valueUsd: 2800, probability: 10, expectedClose: "2026-11-05", nextAction: "Job-board draft", owner: "You", notes: "", lostReason: "", createdAt: "2026-09-15" },
  { id: "deal-11", leadId: "lead-11", title: "Lumen generalist", stage: "lost", valueUsd: 900, probability: 0, expectedClose: "2026-08-28", nextAction: "—", owner: "You", notes: "", lostReason: "Wanted cheap labour, not an outcome", createdAt: "2026-08-20" },
  { id: "deal-12", leadId: "lead-12", title: "Aster recall desk", stage: "negotiation", valueUsd: 3600, probability: 45, expectedClose: "2026-09-25", nextAction: "Hold 45% margin", owner: "You", notes: "Pilot volume offer ready.", lostReason: "", createdAt: "2026-08-28" },
];

export const SEED_OFFERS: Offer[] = [
  {
    id: "off-01",
    name: "Consult Desk",
    service: "appointment_setting",
    industry: "Healthcare / home services",
    deliverables: "30 qualified appointments / month, calendar on their CRM, Friday report, no-show chase.",
    workload: "2 setters, ~80 hours",
    quotedHoursPerMonth: 160,
    vendorCostUsd: 1600,
    desiredMarginPct: 55,
    sla: "priority",
    timeline: "Live in 10 working days",
    priceUsd: 4200,
    upsells: "Recall campaigns; second clinic; SMS confirmations",
    riskWarnings: "No-show rate above 25% needs a reminder stack they must approve.",
    copy: "We fill the chairs. You run the clinic.",
    createdAt: "2026-04-01",
  },
  {
    id: "off-02",
    name: "After-hours CX",
    service: "chat_email_support",
    industry: "Logistics / DTC",
    deliverables: "12-hour coverage, first response < 15 min, macros, daily CSAT sample.",
    workload: "3 agents overlapping US hours",
    quotedHoursPerMonth: 360,
    vendorCostUsd: 2400,
    desiredMarginPct: 58,
    sla: "priority",
    timeline: "Live in 14 days",
    priceUsd: 6800,
    upsells: "Weekend cover; voice overflow",
    riskWarnings: "Product knowledge dump must land in week 0 or CSAT will dip.",
    copy: "Your engineers stop answering ‘where is my shipment’ at 21:00.",
    createdAt: "2026-04-01",
  },
  {
    id: "off-03",
    name: "Buyer List",
    service: "lead_generation",
    industry: "Wholesale / B2B",
    deliverables: "40 verified buyers / month, first-touch drafts (you send), bounce < 4%.",
    workload: "1 researcher + copy desk",
    quotedHoursPerMonth: 100,
    vendorCostUsd: 1400,
    desiredMarginPct: 52,
    sla: "standard",
    timeline: "First list in 7 days",
    priceUsd: 3500,
    upsells: "Appointment setting on the same list",
    riskWarnings: "We do not auto-send. If they want spray, walk.",
    copy: "A list you can stand behind, and copy you still approve.",
    createdAt: "2026-06-01",
  },
  {
    id: "off-04",
    name: "Chambers Pack",
    service: "admin_va",
    industry: "Legal / professional",
    deliverables: "Diary, bundling, billing pack prep, 24h turnaround on named tasks.",
    workload: "1 senior VA + backup",
    quotedHoursPerMonth: 90,
    vendorCostUsd: 1200,
    desiredMarginPct: 50,
    sla: "white_glove",
    timeline: "Live in 8 days after NDA",
    priceUsd: 2900,
    upsells: "Second chambers; transcription",
    riskWarnings: "No vendor-client contact. Access logged.",
    copy: "Fee-earners stay on the law. We stay on the pack.",
    createdAt: "2026-03-20",
  },
];

export const SEED_VENDORS: Vendor[] = [
  { id: "ven-01", name: "Lina Cruz", email: "lina@vendors.example", country: "Philippines", timezone: "PHT", skills: ["Appointment setting", "CRM", "Healthcare"], rateUsd: 1600, rateType: "monthly", availability: "booked", rating: 4.8, testTask: "92 — clinic recall", notes: "Best closer voice. Backup: ven-06.", nda: true, performance: 91, assignedClientIds: ["cli-01"] },
  { id: "ven-02", name: "Arjun Mehta", email: "arjun@vendors.example", country: "India", timezone: "IST", skills: ["CX", "Zendesk", "Logistics"], rateUsd: 2400, rateType: "monthly", availability: "booked", rating: 4.6, testTask: "88 — ticket sample", notes: "Needs product glossary in week 0.", nda: true, performance: 84, assignedClientIds: ["cli-02"] },
  { id: "ven-03", name: "Nadia Rahman", email: "nadia@vendors.example", country: "Bangladesh", timezone: "BST", skills: ["Lead research", "LinkedIn", "Lists"], rateUsd: 14, rateType: "hourly", availability: "booked", rating: 4.7, testTask: "90 — 20-row list", notes: "Does not send. Drafts only.", nda: true, performance: 89, assignedClientIds: ["cli-03"] },
  { id: "ven-04", name: "Sipho Dlamini", email: "sipho@vendors.example", country: "South Africa", timezone: "SAST", skills: ["Legal admin", "Docs", "Diaries"], rateUsd: 1200, rateType: "monthly", availability: "booked", rating: 4.9, testTask: "95 — bundle", notes: "Overlap with UK mornings. Preferred for confidential work.", nda: true, performance: 94, assignedClientIds: ["cli-04"] },
  { id: "ven-05", name: "Mei Tan", email: "mei@vendors.example", country: "Malaysia", timezone: "MYT", skills: ["Chat", "DTC", "Returns"], rateUsd: 1700, rateType: "monthly", availability: "available", rating: 4.5, testTask: "86 — Intercom macros", notes: "Peak-season backup.", nda: true, performance: 82, assignedClientIds: [] },
  { id: "ven-06", name: "Carla Reyes", email: "carla@vendors.example", country: "Philippines", timezone: "PHT", skills: ["Appointment setting", "Home services"], rateUsd: 1500, rateType: "monthly", availability: "limited", rating: 4.4, testTask: "81 — HVAC estimates", notes: "Backup for Lina. Half-time available.", nda: true, performance: 80, assignedClientIds: [] },
  { id: "ven-07", name: "Owen Blake", email: "owen@vendors.example", country: "South Africa", timezone: "SAST", skills: ["Bookkeeping", "Xero"], rateUsd: 700, rateType: "monthly", availability: "available", rating: 4.6, testTask: "89 — recs", notes: "Not assigned. Ready for bookkeeping offer.", nda: false, performance: 87, assignedClientIds: [] },
];

export const SEED_CLIENTS: Client[] = [
  { id: "cli-01", company: "Northbridge Dental Group", country: "United Kingdom", industry: "Healthcare", contactName: "Rachel Cole", email: "rachel.cole@northbridge.example", offerId: "off-01", monthlyFeeUsd: 4200, vendorId: "ven-01", sla: "priority", startDate: "2026-06-20", status: "active", csat: 4.7, notes: "Expanding to a sixth clinic in Q4.", toolCostUsd: 80, otherCostUsd: 0, quotedHoursPerMonth: 160, invoiceStatus: "current" },
  { id: "cli-02", company: "Helios Freight", country: "United States", industry: "Logistics", contactName: "Marcus Hale", email: "mhale@heliosfreight.example", offerId: "off-02", monthlyFeeUsd: 6800, vendorId: "ven-02", sla: "priority", startDate: "2026-05-20", status: "at_risk", csat: 3.9, notes: "CSAT dip after a product change. Coaching this week. Weekend cover added.", toolCostUsd: 120, otherCostUsd: 40, quotedHoursPerMonth: 360, invoiceStatus: "current" },
  { id: "cli-03", company: "Oak & Pine Interiors", country: "Australia", industry: "Retail", contactName: "Elena Park", email: "elena@oakandpine.example", offerId: "off-03", monthlyFeeUsd: 3500, vendorId: "ven-03", sla: "standard", startDate: "2026-07-12", status: "active", csat: 4.8, notes: "Wants appointment setting next.", toolCostUsd: 60, otherCostUsd: 0, quotedHoursPerMonth: 100, invoiceStatus: "current" },
  { id: "cli-04", company: "Meridian Chambers", country: "United Kingdom", industry: "Legal", contactName: "James Whitaker", email: "j.whitaker@meridianchambers.example", offerId: "off-04", monthlyFeeUsd: 2900, vendorId: "ven-04", sla: "white_glove", startDate: "2026-05-02", status: "active", csat: 4.9, notes: "Do not add vendors to the client thread.", toolCostUsd: 40, otherCostUsd: 0, quotedHoursPerMonth: 90, invoiceStatus: "overdue" },
];

export const SEED_TASKS: Task[] = [
  { id: "tsk-01", title: "Friday report — Northbridge", clientId: "cli-01", vendorId: "ven-01", dueAt: "2026-09-19", status: "open", priority: "normal", notes: "Include sixth-clinic capacity." },
  { id: "tsk-02", title: "Helios CSAT recovery sample", clientId: "cli-02", vendorId: "ven-02", dueAt: "2026-09-16", status: "in_progress", priority: "high", notes: "10 tickets, scorecard CX-A." },
  { id: "tsk-03", title: "Oak & Pine September buyer list", clientId: "cli-03", vendorId: "ven-03", dueAt: "2026-09-18", status: "in_progress", priority: "high", notes: "UK lighting buyers." },
  { id: "tsk-04", title: "Meridian overdue invoice chase", clientId: "cli-04", vendorId: "ven-04", dueAt: "2026-09-16", status: "open", priority: "high", notes: "Net 14, 6 days late. Pause new scope until paid." },
  { id: "tsk-05", title: "Brightlane proposal nudge", clientId: "", vendorId: "", dueAt: "2026-09-17", status: "open", priority: "normal", notes: "Lead-05." },
  { id: "tsk-06", title: "Kestrel discovery pack", clientId: "", vendorId: "", dueAt: "2026-09-17", status: "open", priority: "high", notes: "Audit printout + SLA draft." },
  { id: "tsk-07", title: "Vendor PIP — Arjun (Helios)", clientId: "cli-02", vendorId: "ven-02", dueAt: "2026-09-20", status: "open", priority: "high", notes: "Score 84 and falling." },
  { id: "tsk-08", title: "NDA chase — Owen Blake", clientId: "", vendorId: "ven-07", dueAt: "2026-09-18", status: "open", priority: "low", notes: "Cannot assign until signed." },
];

export const SEED_QA: QaReview[] = [
  { id: "qa-01", kind: "appointments", clientId: "cli-01", vendorId: "ven-01", score: 93, mistakes: "One slot booked outside ICP (student enquiry).", coaching: "Re-state ICP on the open of every call.", clientImpact: "Low — cancelled and replaced.", followUp: "None", createdAt: "2026-09-12" },
  { id: "qa-02", kind: "tickets", clientId: "cli-02", vendorId: "ven-02", score: 74, mistakes: "Two macros used on a claims exception. Tone flat on delay emails.", coaching: "Exception path is playbook v3 §4. Tone card attached.", clientImpact: "CSAT 3.9. Two complaints.", followUp: "PIP 14 days. Daily sample.", createdAt: "2026-09-14" },
  { id: "qa-03", kind: "leads", clientId: "cli-03", vendorId: "ven-03", score: 91, mistakes: "Three rows with generic titles.", coaching: "Verify title against About page.", clientImpact: "None — caught before send.", followUp: "Spot-check 5 rows.", createdAt: "2026-09-11" },
];

export const SEED_PROPOSALS: Proposal[] = [
  {
    id: "prop-01",
    leadId: "lead-05",
    offerId: "off-01",
    title: "Brightlane — Consult desk",
    problem: "SDR ramp is slower than the closer calendar. Mornings are empty. CAC is climbing because unprepared traffic is hitting sales.",
    solution: "A dedicated consult desk that books 40 qualified homeowner conversations a month onto your closers’ calendars. You approve the ICP. We do not spray.",
    deliverables: "40 qualified appointments; CRM notes; no-show chase; Friday dashboard; weekly 20-min ops call.",
    timeline: "Days 1–5 access and playbook. Days 6–10 first live week. Month 1 is a measured ramp to 40.",
    pricing: "Setup $1,200 (once). Retainer $5,400 / month. Paid before work starts.",
    sla: "Qualified = homeowner in service area, 20-min slot, source recorded. First response 4 business hours. Two reschedules max.",
    reporting: "Friday 16:00 SAST dashboard + 20-min call.",
    terms: "30-day rolling after month 2. Work starts when setup + month 1 clear. Vendor has no client contact.",
    nextSteps: "Confirm ICP. Pay setup. Kickoff Tuesday.",
    status: "sent",
    createdAt: "2026-09-12",
  },
  {
    id: "prop-02",
    leadId: "lead-12",
    offerId: "off-01",
    title: "Aster Clinics — Recall desk",
    problem: "No-shows and unfilled hygienist books. Reception cannot run a recall cadence and the front desk together.",
    solution: "Recall + new-patient appointment desk. Outcome: 25 kept appointments / month.",
    deliverables: "Recall list worked twice weekly; new-patient inbound; SMS confirmations if you enable them.",
    timeline: "Live in 10 working days.",
    pricing: "Setup $800. Retainer $3,600 / month. We will not drop under 45% gross — a cheaper number is a worse desk.",
    sla: "Kept appointments, not just booked. No-show chase same day.",
    reporting: "Friday report.",
    terms: "Pilot 30 days at full rate. Then rolling.",
    nextSteps: "Accept the 45% floor or we pass.",
    status: "sent",
    createdAt: "2026-09-08",
  },
];

export const SEED_ACTIVITIES: Activity[] = [
  { id: "act-01", at: "2026-09-15T08:10:00", kind: "lead", refId: "lead-10", text: "Copperline HVAC added from job board. Reframed as booked estimates." },
  { id: "act-02", at: "2026-09-14T16:40:00", kind: "qa", refId: "qa-02", text: "Helios QA 74. PIP opened on Arjun." },
  { id: "act-03", at: "2026-09-12T11:00:00", kind: "proposal", refId: "prop-01", text: "Brightlane proposal v2 sent." },
  { id: "act-04", at: "2026-09-11T09:20:00", kind: "client", refId: "cli-04", text: "Meridian invoice marked overdue." },
];

export const SEED_REQUESTS: ClientRequest[] = [
  { id: "req-01", clientId: "cli-01", at: "2026-09-14", title: "Sixth clinic in Leeds", body: "Can the desk cover a sixth book from November?", status: "open" },
  { id: "req-02", clientId: "cli-03", at: "2026-09-10", title: "US lighting buyers", body: "Prioritise West Coast wholesale this month.", status: "done" },
];

export const SEED_REPORTS: ClientReport[] = [
  {
    id: "rep-01",
    clientId: "cli-01",
    period: "1–7 Sep 2026",
    summary: "28 consults kept of 32 booked. Two no-shows recovered. Leeds book still thin — recall list attached.",
    kpis: [
      { label: "Kept appointments", value: "28" },
      { label: "No-show rate", value: "12%" },
      { label: "First response", value: "11 min" },
      { label: "QA", value: "93" },
    ],
  },
  {
    id: "rep-02",
    clientId: "cli-02",
    period: "1–7 Sep 2026",
    summary: "Coverage held. CSAT dropped on delay emails after the claims-process change. Playbook v3 in coaching.",
    kpis: [
      { label: "Tickets closed", value: "412" },
      { label: "First response", value: "09 min" },
      { label: "CSAT", value: "3.9" },
      { label: "QA", value: "74" },
    ],
  },
];

export const SEED_OUTREACH: OutreachDraft[] = [
  {
    id: "out-01",
    leadId: "lead-08",
    tone: "direct",
    channel: "email",
    subject: "Nimbus Intercom is empty after 17:00 PT",
    body: "Ava — I opened Nimbus after hours. Intercom greets, nobody answers. Returns season will multiply that.\n\nWe run a 12-hour chat/email desk for DTC brands. First response under 15 minutes, macros you approve, a Friday number you can take to the founder.\n\nI can send a one-page plan with price and SLA. Want it this week?\n\n— Apexline\n(Draft — you send this. Apexline does not.)",
    createdAt: "2026-09-10",
  },
];

export const SEED_AUDITS: AuditResult[] = [
  {
    id: "aud-01",
    leadId: "lead-06",
    url: "https://kestrel.example",
    business: "B2B analytics SaaS. Self-serve plus a CS team of two engineers.",
    bottlenecks: ["No live chat", "Docs thin on billing", "Engineers handling L1", "First response implied > 8h from the support page"],
    opportunities: ["L1 chat/email desk", "Macro library", "Escalation path that protects engineering"],
    package: "After-hours CX adapted for SaaS L1",
    monthlyValueUsd: 4800,
    angle: "Give engineering their evenings back without hiring a full US CS team.",
    emailDraft: "Priya — two engineers on L1 is a product tax. We can take the first line, report weekly, escalate only when the playbook says so.",
    linkedinDraft: "Priya — glanced at Kestrel support. Engineers on L1. We run that desk. 12 minutes this week?",
    callOpener: "If L1 vanished from engineering’s calendar next month, what would they ship?",
    proposalSummary: "L1 coverage, 12h, macros, 15-min first response, weekly QA.",
    createdAt: "2026-09-08",
  },
];

/**
 * September 2026 so far, covering every state the Effort desk has to show:
 * Northbridge on track; Helios past its hours on a monthly vendor, where the
 * cost is unchanged but the renewal and quality risk is real; Oak & Pine past
 * its hours on an hourly vendor, where margin is leaving this month; and
 * Meridian with nothing logged, the honest "not measured yet" state.
 */
export const SEED_TIME: TimeEntry[] = [
  { id: "te-01", clientId: "cli-01", vendorId: "ven-01", date: "2026-09-01", hours: 38, note: "Week 1 — recall calls, 42 booked." },
  { id: "te-02", clientId: "cli-01", vendorId: "ven-01", date: "2026-09-08", hours: 40, note: "Week 2 — hygienist gaps cleared." },
  { id: "te-03", clientId: "cli-01", vendorId: "ven-01", date: "2026-09-15", hours: 40, note: "Week 3 — sixth clinic prep." },

  { id: "te-04", clientId: "cli-02", vendorId: "ven-02", date: "2026-09-01", hours: 96, note: "Week 1 — normal volume." },
  { id: "te-05", clientId: "cli-02", vendorId: "ven-02", date: "2026-09-08", hours: 132, note: "Week 2 — product change, ticket spike. Weekend cover added." },
  { id: "te-06", clientId: "cli-02", vendorId: "ven-02", date: "2026-09-15", hours: 141, note: "Week 3 — backlog plus coaching hours. Nobody re-priced this." },

  { id: "te-07", clientId: "cli-03", vendorId: "ven-03", date: "2026-09-02", hours: 26, note: "September list — 40 verified buyers." },
  { id: "te-08", clientId: "cli-03", vendorId: "ven-03", date: "2026-09-09", hours: 44, note: "Client changed the ICP. List rebuilt from scratch — not re-quoted." },
  { id: "te-09", clientId: "cli-03", vendorId: "ven-03", date: "2026-09-15", hours: 42, note: "Second rebuild after the ICP moved again. Still on the original price." },
];
