/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ProfitRouteImport } from './routes/profit'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as QaRouteImport } from './routes/qa'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'
import { Route as ProposalsIndexRouteImport } from './routes/proposals.index'
import { Route as ProposalsProposalIdRouteImport } from './routes/proposals.$proposalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitRoute = ProfitRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeadsRoute,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => LeadsRoute,
} as any)
const ProposalsIndexRoute = ProposalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProposalsRoute,
} as any)
const ProposalsProposalIdRoute = ProposalsProposalIdRouteImport.update({
  id: '/$proposalId',
  path: '/$proposalId',
  getParentRoute: () => ProposalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/clients': typeof ClientsRouteWithChildren
  '/leads': typeof LeadsRouteWithChildren
  '/offers': typeof OffersRoute
  '/outreach': typeof OutreachRoute
  '/pipeline': typeof PipelineRoute
  '/portal': typeof PortalRoute
  '/profit': typeof ProfitRoute
  '/proposals': typeof ProposalsRouteWithChildren
  '/qa': typeof QaRoute
  '/services': typeof ServicesRoute
  '/tasks': typeof TasksRoute
  '/templates': typeof TemplatesRoute
  '/vendors': typeof VendorsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/proposals/$proposalId': typeof ProposalsProposalIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/proposals/': typeof ProposalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/offers': typeof OffersRoute
  '/outreach': typeof OutreachRoute
  '/pipeline': typeof PipelineRoute
  '/portal': typeof PortalRoute
  '/profit': typeof ProfitRoute
  '/qa': typeof QaRoute
  '/services': typeof ServicesRoute
  '/tasks': typeof TasksRoute
  '/templates': typeof TemplatesRoute
  '/vendors': typeof VendorsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/proposals/$proposalId': typeof ProposalsProposalIdRoute
  '/clients': typeof ClientsIndexRoute
  '/leads': typeof LeadsIndexRoute
  '/proposals': typeof ProposalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/clients': typeof ClientsRouteWithChildren
  '/leads': typeof LeadsRouteWithChildren
  '/offers': typeof OffersRoute
  '/outreach': typeof OutreachRoute
  '/pipeline': typeof PipelineRoute
  '/portal': typeof PortalRoute
  '/profit': typeof ProfitRoute
  '/proposals': typeof ProposalsRouteWithChildren
  '/qa': typeof QaRoute
  '/services': typeof ServicesRoute
  '/tasks': typeof TasksRoute
  '/templates': typeof TemplatesRoute
  '/vendors': typeof VendorsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/proposals/$proposalId': typeof ProposalsProposalIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/proposals/': typeof ProposalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/audit'
    | '/clients'
    | '/leads'
    | '/offers'
    | '/outreach'
    | '/pipeline'
    | '/portal'
    | '/profit'
    | '/proposals'
    | '/qa'
    | '/services'
    | '/tasks'
    | '/templates'
    | '/vendors'
    | '/clients/$clientId'
    | '/leads/$leadId'
    | '/proposals/$proposalId'
    | '/clients/'
    | '/leads/'
    | '/proposals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/audit'
    | '/offers'
    | '/outreach'
    | '/pipeline'
    | '/portal'
    | '/profit'
    | '/qa'
    | '/services'
    | '/tasks'
    | '/templates'
    | '/vendors'
    | '/clients/$clientId'
    | '/leads/$leadId'
    | '/proposals/$proposalId'
    | '/clients'
    | '/leads'
    | '/proposals'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/audit'
    | '/clients'
    | '/leads'
    | '/offers'
    | '/outreach'
    | '/pipeline'
    | '/portal'
    | '/profit'
    | '/proposals'
    | '/qa'
    | '/services'
    | '/tasks'
    | '/templates'
    | '/vendors'
    | '/clients/$clientId'
    | '/leads/$leadId'
    | '/proposals/$proposalId'
    | '/clients/'
    | '/leads/'
    | '/proposals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AuditRoute: typeof AuditRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  LeadsRoute: typeof LeadsRouteWithChildren
  OffersRoute: typeof OffersRoute
  OutreachRoute: typeof OutreachRoute
  PipelineRoute: typeof PipelineRoute
  PortalRoute: typeof PortalRoute
  ProfitRoute: typeof ProfitRoute
  ProposalsRoute: typeof ProposalsRouteWithChildren
  QaRoute: typeof QaRoute
  ServicesRoute: typeof ServicesRoute
  TasksRoute: typeof TasksRoute
  TemplatesRoute: typeof TemplatesRoute
  VendorsRoute: typeof VendorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profit': {
      id: '/profit'
      path: '/profit'
      fullPath: '/profit'
      preLoaderRoute: typeof ProfitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/leads/': {
      id: '/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/proposals/': {
      id: '/proposals/'
      path: '/'
      fullPath: '/proposals/'
      preLoaderRoute: typeof ProposalsIndexRouteImport
      parentRoute: typeof ProposalsRoute
    }
    '/proposals/$proposalId': {
      id: '/proposals/$proposalId'
      path: '/$proposalId'
      fullPath: '/proposals/$proposalId'
      preLoaderRoute: typeof ProposalsProposalIdRouteImport
      parentRoute: typeof ProposalsRoute
    }
  }
}

interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface LeadsRouteChildren {
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
}

const LeadsRouteChildren: LeadsRouteChildren = {
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  LeadsIndexRoute: LeadsIndexRoute,
}

const LeadsRouteWithChildren = LeadsRoute._addFileChildren(LeadsRouteChildren)

interface ProposalsRouteChildren {
  ProposalsProposalIdRoute: typeof ProposalsProposalIdRoute
  ProposalsIndexRoute: typeof ProposalsIndexRoute
}

const ProposalsRouteChildren: ProposalsRouteChildren = {
  ProposalsProposalIdRoute: ProposalsProposalIdRoute,
  ProposalsIndexRoute: ProposalsIndexRoute,
}

const ProposalsRouteWithChildren = ProposalsRoute._addFileChildren(
  ProposalsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AuditRoute: AuditRoute,
  ClientsRoute: ClientsRouteWithChildren,
  LeadsRoute: LeadsRouteWithChildren,
  OffersRoute: OffersRoute,
  OutreachRoute: OutreachRoute,
  PipelineRoute: PipelineRoute,
  PortalRoute: PortalRoute,
  ProfitRoute: ProfitRoute,
  ProposalsRoute: ProposalsRouteWithChildren,
  QaRoute: QaRoute,
  ServicesRoute: ServicesRoute,
  TasksRoute: TasksRoute,
  TemplatesRoute: TemplatesRoute,
  VendorsRoute: VendorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
